# Generated by Django 3.0.7 on 2021-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating__average', 'created_at']},
        ),
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(default='img/default-cover.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='PG-13', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name="Movie's title"),
        ),
    ]
